-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.DimScenario
CREATE TABLE JAMES.DimScenario
(
 ScenarioKey  number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Scenario Identifier',
 ScenarioName varchar(16777216) COMMENT 'Name of the Scenario',
 CreatedBy    varchar(16777216) NOT NULL COMMENT 'Who Created this Scenario',
 CreatedDate  timestamp_ntz(9) NOT NULL COMMENT 'Scenario Creation Date',
 UpdatedDate  timestamp_ntz(9) NOT NULL,
 UpdatedBy    varchar(16777216) NOT NULL,
 TestCol      varchar(16777216) NOT NULL,

 CONSTRAINT PK_DimScenario PRIMARY KEY ( ScenarioKey )
)
COMMENT = 'Dimension Scenario';

-- ************************************** JAMES.DimSalesTerritory
CREATE TABLE JAMES.DimSalesTerritory
(
 SalesTerritoryKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 SalesTerritoryAlternateKey number(38,0),
 SalesTerritoryRegion       varchar(16777216) NOT NULL,
 SalesTerritoryCountry      varchar(16777216) NOT NULL,
 SalesTerritoryGroup        varchar(16777216),

 CONSTRAINT PK_DimSalesTerritory PRIMARY KEY ( SalesTerritoryKey )
)
COMMENT = 'Sales Territory data';

-- ************************************** JAMES.DimPromotion
CREATE TABLE JAMES.DimPromotion
(
 PromotionKey             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 PromotionAlternateKey    number(38,0),
 EnglishPromotionName     varchar(16777216),
 SpanishPromotionName     varchar(16777216),
 FrenchPromotionName      varchar(16777216),
 DiscountPct              float,
 EnglishPromotionType     varchar(16777216),
 SpanishPromotionType     varchar(16777216),
 FrenchPromotionType      varchar(16777216),
 EnglishPromotionCategory varchar(16777216),
 SpanishPromotionCategory varchar(16777216),
 FrenchPromotionCategory  varchar(16777216),
 MinQty                   number(38,0),
 MaxQty                   number(38,0),

 CONSTRAINT PK_DimPromotion PRIMARY KEY ( PromotionKey )
);

-- ************************************** JAMES.DimProductPrototype
CREATE TABLE JAMES.DimProductPrototype
(
 DimProductPrototypeKey integer NOT NULL,
 FinishedGoodsFlag      number(38,0) NOT NULL,
 ReorderPoint           number(38,0),
 Weight                 float NOT NULL,
 ModelName              varchar(16777216),

 CONSTRAINT PK_1 PRIMARY KEY ( DimProductPrototypeKey )
);

-- ************************************** JAMES.DimProductCategory
CREATE TABLE JAMES.DimProductCategory
(
 ProductCategoryKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ProductCategoryAlternateKey number(38,0),
 EnglishProductCategoryName  varchar(16777216) NOT NULL,
 SpanishProductCategoryName  varchar(16777216) NOT NULL,
 FrenchProductCategoryName   varchar(16777216) NOT NULL,

 CONSTRAINT PK_DimProductCategory PRIMARY KEY ( ProductCategoryKey )
);

-- ************************************** JAMES.DimOrganization
CREATE TABLE JAMES.DimOrganization
(
 OrganizationKey       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ParentOrganizationKey number(38,0),
 PercentageOfOwnership varchar(16777216),
 OrganizationName      varchar(16777216),
 CurrencyKey           number(38,0),

 CONSTRAINT PK_DimOrganization PRIMARY KEY ( OrganizationKey )
)
COMMENT = 'Dimension for Organizational Data';

-- ************************************** DimInternet
CREATE TABLE DimInternet
(
 id integer NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( id )
);

-- ************************************** JAMES.DimGeography
CREATE TABLE JAMES.DimGeography
(
 GeographyKey             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 City                     varchar(16777216),
 StateProvinceCode        varchar(16777216),
 StateProvinceName        varchar(16777216),
 CountryRegionCode        varchar(16777216),
 EnglishCountryRegionName varchar(16777216),
 SpanishCountryRegionName varchar(16777216),
 FrenchCountryRegionName  varchar(16777216),
 PostalCode               varchar(16777216),
 SalesTerritoryKey        number(38,0),
 IpAddressLocator         varchar(16777216),

 CONSTRAINT PK_DimGeography PRIMARY KEY ( GeographyKey )
);

-- ************************************** JAMES.DimDepartmentGroup
CREATE TABLE JAMES.DimDepartmentGroup
(
 DepartmentGroupKey       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ParentDepartmentGroupKey number(38,0),
 DepartmentGroupName      varchar(16777216),

 CONSTRAINT PK_DimDepartmentGroup PRIMARY KEY ( DepartmentGroupKey )
)
COMMENT = 'Dimension for Department groups';

-- ************************************** JAMES.DimDate
CREATE TABLE JAMES.DimDate
(
 DateKey              number(38,0) NOT NULL,
 FullDateAlternateKey date NOT NULL,
 DayNumberOfWeek      number(38,0) NOT NULL,
 EnglishDayNameOfWeek varchar(16777216) NOT NULL,
 SpanishDayNameOfWeek varchar(16777216) NOT NULL,
 FrenchDayNameOfWeek  varchar(16777216) NOT NULL,
 DayNumberOfMonth     number(38,0) NOT NULL,
 DayNumberOfYear      number(38,0) NOT NULL,
 WeekNumberOfYear     number(38,0) NOT NULL,
 EnglishMonthName     varchar(16777216) NOT NULL,
 SpanishMonthName     varchar(16777216) NOT NULL,
 FrenchMonthName      varchar(16777216) NOT NULL,
 MonthNumberOfYear    number(38,0) NOT NULL,
 CalendarQuarter      number(38,0) NOT NULL,
 CalendarYear         number(38,0) NOT NULL,
 CalendarSemester     number(38,0) NOT NULL,
 FiscalQuarter        number(38,0) NOT NULL,
 FiscalYear           number(38,0) NOT NULL,
 FiscalSemester       number(38,0) NOT NULL,

 CONSTRAINT PK_DimDate PRIMARY KEY ( DateKey )
)
COMMENT = 'Dimension for Date time';

-- ************************************** JAMES.DimCurrency
CREATE TABLE JAMES.DimCurrency
(
 CurrencyKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Currency Identifier',
 CurrencyAlternateKey varchar(16777216) NOT NULL COMMENT 'Alternate Currency Identifier',
 CurrencyName         varchar(16777216) NOT NULL COMMENT 'Name of the Currency',

 CONSTRAINT PK_DimCurrency PRIMARY KEY ( CurrencyKey )
)
COMMENT = 'Dimension for Currency Data';

-- ************************************** JAMES.DimAccount
CREATE TABLE JAMES.DimAccount
(
 AccountKey                    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique Identifier of the Account data',
 ParentAccountKey              number(38,0) COMMENT 'Identifier of parent Account',
 AccountCodeAlternateKey       number(38,0),
 ParentAccountCodeAlternateKey number(38,0),
 AccountDescription            varchar(16777216),
 AccountType                   varchar(16777216),
 Operator                      varchar(16777216),
 CustomMembers                 varchar(16777216),
 ValueType                     varchar(16777216),
 CustomMemberOptions           varchar(16777216),

 CONSTRAINT PK_DimAccount PRIMARY KEY ( AccountKey )
)
COMMENT = 'Holds all Account information';

-- ************************************** JAMES.NewFactCurrencyRate
CREATE TABLE JAMES.NewFactCurrencyRate
(
 AverageRate  float,
 CurrencyID   varchar(16777216),
 CurrencyDate date,
 EndOfDayRate float,
 CurrencyKey  number(38,0),
 DateKey      number(38,0),

 CONSTRAINT FK_NewFactCurrencyRate_469 FOREIGN KEY ( CurrencyKey ) REFERENCES JAMES.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_NewFactCurrencyRate_471 FOREIGN KEY ( DateKey ) REFERENCES JAMES.DimDate ( DateKey )
);

-- ************************************** JAMES.FactSurveyResponse
CREATE TABLE JAMES.FactSurveyResponse
(
 SurveyResponseKey             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 DateKey                       number(38,0) NOT NULL,
 CustomerKey                   number(38,0) NOT NULL,
 ProductCategoryKey            number(38,0) NOT NULL,
 EnglishProductCategoryName    varchar(16777216) NOT NULL,
 ProductSubcategoryKey         number(38,0) NOT NULL,
 EnglishProductSubcategoryName varchar(16777216) NOT NULL,

 CONSTRAINT FK_FactSurveyResponse_465 FOREIGN KEY ( DateKey ) REFERENCES JAMES.DimDate ( DateKey ),
 CONSTRAINT FK_FactSurveyResponse_467 FOREIGN KEY ( ProductCategoryKey ) REFERENCES JAMES.DimProductCategory ( ProductCategoryKey )
);

-- ************************************** JAMES.FactSalesQuota
CREATE TABLE JAMES.FactSalesQuota
(
 SalesQuotaKey    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 EmployeeKey      number(38,0) NOT NULL,
 DateKey          number(38,0) NOT NULL,
 CalendarYear     number(38,0) NOT NULL,
 CalendarQuarter  number(38,0) NOT NULL,
 SalesAmountQuota number(38,0) NOT NULL,

 CONSTRAINT FK_FactSalesQuota_463 FOREIGN KEY ( DateKey ) REFERENCES JAMES.DimDate ( DateKey )
);

-- ************************************** JAMES.FactProductInventory
CREATE TABLE JAMES.FactProductInventory
(
 ProductKey   number(38,0) NOT NULL,
 DateKey      number(38,0) NOT NULL,
 MovementDate date NOT NULL,
 UnitCost     number(38,0) NOT NULL,
 UnitsIn      number(38,0) NOT NULL,
 UnitsOut     number(38,0) NOT NULL,
 UnitsBalance number(38,0) NOT NULL,

 CONSTRAINT FK_FactProductInventory_443 FOREIGN KEY ( DateKey ) REFERENCES JAMES.DimDate ( DateKey )
);

-- ************************************** JAMES.FactFinance
CREATE TABLE JAMES.FactFinance
(
 FinanceKey         number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 DateKey            number(38,0) NOT NULL,
 OrganizationKey    number(38,0) NOT NULL,
 DepartmentGroupKey number(38,0) NOT NULL,
 ScenarioKey        number(38,0) NOT NULL,
 AccountKey         number(38,0) NOT NULL,
 Amount             float NOT NULL,

 CONSTRAINT FK_FactFinance_417 FOREIGN KEY ( DateKey ) REFERENCES JAMES.DimDate ( DateKey ),
 CONSTRAINT FK_FactFinance_419 FOREIGN KEY ( OrganizationKey ) REFERENCES JAMES.DimOrganization ( OrganizationKey ),
 CONSTRAINT FK_FactFinance_421 FOREIGN KEY ( DepartmentGroupKey ) REFERENCES JAMES.DimDepartmentGroup ( DepartmentGroupKey ),
 CONSTRAINT FK_FactFinance_423 FOREIGN KEY ( ScenarioKey ) REFERENCES JAMES.DimScenario ( ScenarioKey ),
 CONSTRAINT FK_FactFinance_425 FOREIGN KEY ( AccountKey ) REFERENCES JAMES.DimAccount ( AccountKey )
)
COMMENT = 'Facts for Finance';

-- ************************************** JAMES.FactCurrencyRate
CREATE TABLE JAMES.FactCurrencyRate
(
 CurrencyKey  number(38,0) NOT NULL,
 DateKey      number(38,0) NOT NULL,
 AverageRate  float NOT NULL,
 EndOfDayRate float NOT NULL,

 CONSTRAINT FK_FactCurrencyRate_413 FOREIGN KEY ( CurrencyKey ) REFERENCES JAMES.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_FactCurrencyRate_415 FOREIGN KEY ( DateKey ) REFERENCES JAMES.DimDate ( DateKey )
);

-- ************************************** JAMES.DimReseller
CREATE TABLE JAMES.DimReseller
(
 ResellerKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 GeographyKey         number(38,0),
 ResellerAlternateKey varchar(16777216),
 Phone                varchar(16777216),
 BusinessType         varchar(16777216) NOT NULL,
 ResellerName         varchar(16777216) NOT NULL,
 NumberEmployees      number(38,0),
 OrderFrequency       varchar(16777216),
 OrderMonth           number(38,0),
 FirstOrderYear       number(38,0),
 LastOrderYear        number(38,0),
 ProductLine          varchar(16777216),
 AddressLine1         varchar(16777216),
 AddressLine2         varchar(16777216),
 AnnualSales          number(38,0),
 BankName             varchar(16777216),
 MinPaymentType       number(38,0),
 MinPaymentAmount     number(38,0),
 AnnualRevenue        number(38,0),
 YearOpened           number(38,0),

 CONSTRAINT PK_DimReseller PRIMARY KEY ( ResellerKey ),
 CONSTRAINT FK_DimReseller_411 FOREIGN KEY ( GeographyKey ) REFERENCES JAMES.DimGeography ( GeographyKey )
);

-- ************************************** JAMES.DimProductSubcategory
CREATE TABLE JAMES.DimProductSubcategory
(
 ProductSubcategoryKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ProductSubcategoryAlternateKey number(38,0),
 EnglishProductSubcategoryName  varchar(16777216) NOT NULL,
 SpanishProductSubcategoryName  varchar(16777216) NOT NULL,
 FrenchProductSubcategoryName   varchar(16777216) NOT NULL,
 ProductCategoryKey             number(38,0),

 CONSTRAINT PK_DimProductSubcategory PRIMARY KEY ( ProductSubcategoryKey ),
 CONSTRAINT FK_DimProductSubcategory_409 FOREIGN KEY ( ProductCategoryKey ) REFERENCES JAMES.DimProductCategory ( ProductCategoryKey )
);

-- ************************************** JAMES.DimEmployee
CREATE TABLE JAMES.DimEmployee
(
 EmployeeKey                          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ParentEmployeeKey                    number(38,0),
 EmployeeNationalIDAlternateKey       varchar(16777216),
 ParentEmployeeNationalIDAlternateKey varchar(16777216),
 SalesTerritoryKey                    number(38,0),
 FirstName                            varchar(16777216) NOT NULL,
 LastName                             varchar(16777216) NOT NULL,
 MiddleName                           varchar(16777216),
 NameStyle                            number(38,0) NOT NULL,
 Title                                varchar(16777216),
 HireDate                             date,
 BirthDate                            date,
 LoginID                              varchar(16777216),
 EmailAddress                         varchar(16777216),
 Phone                                varchar(16777216),
 MaritalStatus                        varchar(16777216),
 EmergencyContactName                 varchar(16777216),
 EmergencyContactPhone                varchar(16777216),
 SalariedFlag                         number(38,0),
 Gender                               varchar(16777216),
 PayFrequency                         number(38,0),
 BaseRate                             number(38,0),
 VacationHours                        number(38,0),
 SickLeaveHours                       number(38,0),
 CurrentFlag                          number(38,0) NOT NULL,
 SalesPersonFlag                      number(38,0) NOT NULL,
 DepartmentName                       varchar(16777216),
 StartDate                            date,
 EndDate                              date,
 Status                               varchar(16777216),

 CONSTRAINT PK_DimEmployee PRIMARY KEY ( EmployeeKey ),
 CONSTRAINT FK_DimEmployee_403 FOREIGN KEY ( ParentEmployeeKey ) REFERENCES JAMES.DimEmployee ( EmployeeKey ),
 CONSTRAINT FK_DimEmployee_405 FOREIGN KEY ( SalesTerritoryKey ) REFERENCES JAMES.DimSalesTerritory ( SalesTerritoryKey )
)
COMMENT = 'This table holds all Employee Information';

-- ************************************** JAMES.DimCustomer
CREATE TABLE JAMES.DimCustomer
(
 CustomerKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Customer Identifier',
 GeographyKey         number(38,0) COMMENT 'Geographic informatio',
 CustomerAlternateKey varchar(16777216) NOT NULL COMMENT 'Alternate Key',
 Title                varchar(16777216) COMMENT 'Title of the Customer',
 FirstName            varchar(16777216),
 MiddleName           varchar(16777216),
 LastName             varchar(16777216),
 NameStyle            varchar(16777216),
 BirthDate            date,
 MaritalStatus        varchar(16777216),
 Suffix               varchar(16777216),
 Gender               varchar(16777216),
 EmailAddress         varchar(16777216),
 YearlyIncome         number(38,0),
 TotalChildren        number(38,0),
 NumberChildrenAtHome number(38,0),
 EnglishEducation     varchar(16777216),
 SpanishEducation     varchar(16777216),
 FrenchEducation      varchar(16777216),
 EnglishOccupation    varchar(16777216),
 SpanishOccupation    varchar(16777216),
 FrenchOccupation     varchar(16777216),
 HouseOwnerFlag       varchar(16777216),
 NumberCarsOwned      number(38,0),
 AddressLine          varchar(16777216),
 AddressLine2         varchar(16777216),
 Phone                varchar(16777216),
 DateFirstPurchase    date,
 CommuteDistance      varchar(16777216),

 CONSTRAINT PK_DimCustomer PRIMARY KEY ( CustomerKey ),
 CONSTRAINT FK_DimCustomer_401 FOREIGN KEY ( GeographyKey ) REFERENCES JAMES.DimGeography ( GeographyKey )
)
COMMENT = 'Dimension for Customer Data';

-- ************************************** JAMES.DimProduct
CREATE TABLE JAMES.DimProduct
(
 ProductKey             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 DimProductPrototypeKey integer NOT NULL,
 ProductAlternateKey    varchar(16777216),
 ProductSubcategoryKey  number(38,0),
 WeightUnitMeasureCode  varchar(16777216),
 SizeUnitMeasureCode    varchar(16777216),
 EnglishProductName     varchar(16777216) NOT NULL,
 SpanishProductName     varchar(16777216),
 FrenchProductName      varchar(16777216),
 StandardCost           number(38,0),
 Color                  varchar(16777216) NOT NULL,
 SafetyStockLevel       number(38,0),
 ListPrice              number(38,0),
 Size                   varchar(16777216),
 SizeRange              varchar(16777216),
 DaysToManufacture      number(38,0),
 ProductLine            varchar(16777216),
 DealerPrice            number(38,0),
 Class                  varchar(16777216),
 Style                  varchar(16777216),
 EnglishDescription     varchar(16777216),
 FrenchDescription      varchar(16777216),
 ChineseDescription     varchar(16777216),
 ArabicDescription      varchar(16777216),
 HebrewDescription      varchar(16777216),
 ThaiDescription        varchar(16777216),
 GermanDescription      varchar(16777216),
 JapaneseDescription    varchar(16777216),
 TurkishDescription     varchar(16777216),
 Status                 varchar(16777216),

 CONSTRAINT PK_DimProduct PRIMARY KEY ( ProductKey, DimProductPrototypeKey ),
 CONSTRAINT FK_37 FOREIGN KEY ( DimProductPrototypeKey ) REFERENCES JAMES.DimProductPrototype ( DimProductPrototypeKey ),
 CONSTRAINT FK_DimProduct_407 FOREIGN KEY ( ProductSubcategoryKey ) REFERENCES JAMES.DimProductSubcategory ( ProductSubcategoryKey )
);

-- ************************************** JAMES.FactResellerSales
CREATE TABLE JAMES.FactResellerSales
(
 ProductKey             number(38,0) NOT NULL,
 OrderDateKey           number(38,0) NOT NULL,
 DueDateKey             number(38,0) NOT NULL,
 ShipDateKey            number(38,0) NOT NULL,
 ResellerKey            number(38,0) NOT NULL,
 EmployeeKey            number(38,0) NOT NULL,
 PromotionKey           number(38,0) NOT NULL,
 CurrencyKey            number(38,0) NOT NULL,
 SalesTerritoryKey      number(38,0) NOT NULL,
 SalesOrderNumber       varchar(16777216) NOT NULL,
 SalesOrderLineNumber   number(38,0) NOT NULL,
 RevisionNumber         number(38,0),
 OrderQuantity          number(38,0),
 UnitPrice              number(38,0),
 ExtendedAmount         number(38,0),
 UnitPriceDiscountPct   float,
 DiscountAmount         float,
 ProductStandardCost    number(38,0),
 TotalProductCost       number(38,0),
 SalesAmount            number(38,0),
 TaxAmt                 number(38,0),
 Freight                number(38,0),
 CarrierTrackingNumber  varchar(16777216),
 CustomerPONumber       varchar(16777216),
 DimProductPrototypeKey integer NOT NULL,

 CONSTRAINT FK_FactResellerSales_445 FOREIGN KEY ( ProductKey, DimProductPrototypeKey ) REFERENCES JAMES.DimProduct ( ProductKey, DimProductPrototypeKey ),
 CONSTRAINT FK_FactResellerSales_447 FOREIGN KEY ( ResellerKey ) REFERENCES JAMES.DimReseller ( ResellerKey ),
 CONSTRAINT FK_FactResellerSales_449 FOREIGN KEY ( EmployeeKey ) REFERENCES JAMES.DimEmployee ( EmployeeKey ),
 CONSTRAINT FK_FactResellerSales_451 FOREIGN KEY ( PromotionKey ) REFERENCES JAMES.DimPromotion ( PromotionKey ),
 CONSTRAINT FK_FactResellerSales_453 FOREIGN KEY ( CurrencyKey ) REFERENCES JAMES.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_FactResellerSales_455 FOREIGN KEY ( SalesTerritoryKey ) REFERENCES JAMES.DimSalesTerritory ( SalesTerritoryKey ),
 CONSTRAINT FK_FactResellerSales_457 FOREIGN KEY ( OrderDateKey ) REFERENCES JAMES.DimDate ( DateKey ),
 CONSTRAINT FK_FactResellerSales_459 FOREIGN KEY ( DueDateKey ) REFERENCES JAMES.DimDate ( DateKey ),
 CONSTRAINT FK_FactResellerSales_461 FOREIGN KEY ( ShipDateKey ) REFERENCES JAMES.DimDate ( DateKey )
)
COMMENT = 'Fact data of Reseller Sales';

-- ************************************** JAMES.FactInternetSales
CREATE TABLE JAMES.FactInternetSales
(
 ProductKey             number(38,0) NOT NULL,
 OrderDateKey           number(38,0) NOT NULL,
 DueDateKey             number(38,0) NOT NULL,
 ShipDateKey            number(38,0) NOT NULL,
 CustomerKey            number(38,0) NOT NULL,
 PromotionKey           number(38,0) NOT NULL,
 CurrencyKey            number(38,0) NOT NULL,
 SalesTerritoryKey      number(38,0) NOT NULL,
 SalesOrderNumber       varchar(16777216) NOT NULL,
 SalesOrderLineNumber   number(38,0) NOT NULL,
 RevisionNumber         number(38,0) NOT NULL,
 OrderQuantity          number(38,0) NOT NULL,
 UnitPrice              number(38,0) NOT NULL,
 ExtendedAmount         number(38,0) NOT NULL,
 UnitPriceDiscountPct   float NOT NULL,
 DiscountAmount         float NOT NULL,
 ProductStandardCost    number(38,0) NOT NULL,
 TotalProductCost       number(38,0) NOT NULL,
 SalesAmount            number(38,0) NOT NULL,
 TaxAmt                 number(38,0) NOT NULL,
 Freight                number(38,0) NOT NULL,
 CarrierTrackingNumber  varchar(16777216),
 CustomerPONumber       varchar(16777216),
 DimProductPrototypeKey integer NOT NULL,

 CONSTRAINT FK_FactInternetSales_427 FOREIGN KEY ( ProductKey, DimProductPrototypeKey ) REFERENCES JAMES.DimProduct ( ProductKey, DimProductPrototypeKey ),
 CONSTRAINT FK_FactInternetSales_429 FOREIGN KEY ( CustomerKey ) REFERENCES JAMES.DimCustomer ( CustomerKey ),
 CONSTRAINT FK_FactInternetSales_431 FOREIGN KEY ( PromotionKey ) REFERENCES JAMES.DimPromotion ( PromotionKey ),
 CONSTRAINT FK_FactInternetSales_433 FOREIGN KEY ( CurrencyKey ) REFERENCES JAMES.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_FactInternetSales_435 FOREIGN KEY ( SalesTerritoryKey ) REFERENCES JAMES.DimSalesTerritory ( SalesTerritoryKey ),
 CONSTRAINT FK_FactInternetSales_437 FOREIGN KEY ( OrderDateKey ) REFERENCES JAMES.DimDate ( DateKey ),
 CONSTRAINT FK_FactInternetSales_439 FOREIGN KEY ( DueDateKey ) REFERENCES JAMES.DimDate ( DateKey ),
 CONSTRAINT FK_FactInternetSales_441 FOREIGN KEY ( ShipDateKey ) REFERENCES JAMES.DimDate ( DateKey )
)
COMMENT = 'Fact table to hold Currency Data';

