-- ***************************************** SqlDBM: Snowflake ****************************************
-- * Generated by SqlDBM: Snowflake export of ''Logical' project sample 1' by james.boncek@sqldbm.com *

-- ************************************** "CUSTOMER"
CREATE TABLE "CUSTOMER"
(
 "C_CUSTKEY"    number(38,0) NOT NULL COMMENT 'Unique customer identifier',
 "C_NAME"       varchar(16777216) NOT NULL COMMENT 'Name of the customer',
 "C_ADDRESS"    varchar(16777216) NOT NULL COMMENT 'Address of the customer',
 "C_PHONE"      varchar(16777216) NOT NULL COMMENT 'Phone number of the customer',
 "C_ACCTBAL"    number(12,2) NOT NULL COMMENT 'Account balance of the customer',
 "C_MKTSEGMENT" varchar(16777216) NOT NULL COMMENT 'Market segment of the customer',
 "C_COMMENT"    varchar(16777216) COMMENT 'Comment about the customer',
 "C_NATIONKEY"  number(38,0) NOT NULL COMMENT 'Foreign key to LOCATION (N_NATIONKEY)',

 CONSTRAINT "PK_1" PRIMARY KEY ( "C_CUSTKEY" ),
 CONSTRAINT "FK_1" FOREIGN KEY ( "C_NATIONKEY" ) REFERENCES "NATION" ( "N_NATIONKEY" )
)
COMMENT = 'Registered customers';
