-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Snowflake sample awt6u56u8 by james.boncek@sqldbm.com *

-- ************************************** Dim_Customer
CREATE TRANSIENT TABLE Dim_Customer
(
 CustomerId   int NOT NULL,
 CustomerName string NOT NULL,
 Phone        string,

 CONSTRAINT PK_table_2 PRIMARY KEY ( CustomerId )
)
STAGE_FILE_FORMAT =
(
 FORMAT_NAME = 'CsvFileFormat'
);
