-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Snowflake sample awt6u56u8 by james.boncek@sqldbm.com *

-- ************************************** Dim_Order
CREATE TABLE Dim_Order
(
 OrderId     int NOT NULL,
 OrderNumber string NOT NULL,

 CONSTRAINT PK_DIm_Order PRIMARY KEY ( OrderId )
)
STAGE_FILE_FORMAT =
(
 FORMAT_NAME = 'CsvFileFormat'
);
