-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** DimInternet
CREATE TABLE DimInternet
(
 id integer NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( id )
);
