-- ***************************************** SqlDBM: Snowflake ****************************************
-- * Generated by SqlDBM: Snowflake export of ''Logical' project sample 1' by james.boncek@sqldbm.com *

-- ************************************** "INVENTORY"
CREATE TABLE "INVENTORY"
(
 "PS_SUPPKEY"    number(38,0) NOT NULL COMMENT 'Part of the unique identifier with ps_partkey',
 "PS_PARTKEY"    number(38,0) NOT NULL COMMENT 'Part of the unique identifier with ps_suppkey',
 "PS_AVAILQTY"   number(38,0) NOT NULL COMMENT 'Number of parts available for sale',
 "PS_SUPPLYCOST" number(12,2) NOT NULL COMMENT 'Original cost paid to supplier',

 CONSTRAINT "PK_3" PRIMARY KEY ( "PS_SUPPKEY", "PS_PARTKEY" ),
 CONSTRAINT "FK_6" FOREIGN KEY ( "PS_SUPPKEY" ) REFERENCES "SUPPLIER" ( "S_SUPPKEY" ),
 CONSTRAINT "FK_8" FOREIGN KEY ( "PS_PARTKEY" ) REFERENCES "PART" ( "P_PARTKEY" )
)
COMMENT = 'Warehouse Inventory';
