-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.DimCustomer
CREATE TABLE JAMES.DimCustomer
(
 CustomerKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Customer Identifier',
 GeographyKey         number(38,0) COMMENT 'Geographic informatio',
 CustomerAlternateKey varchar(16777216) NOT NULL COMMENT 'Alternate Key',
 Title                varchar(16777216) COMMENT 'Title of the Customer',
 FirstName            varchar(16777216),
 MiddleName           varchar(16777216),
 LastName             varchar(16777216),
 NameStyle            varchar(16777216),
 BirthDate            date,
 MaritalStatus        varchar(16777216),
 Suffix               varchar(16777216),
 Gender               varchar(16777216),
 EmailAddress         varchar(16777216),
 YearlyIncome         number(38,0),
 TotalChildren        number(38,0),
 NumberChildrenAtHome number(38,0),
 EnglishEducation     varchar(16777216),
 SpanishEducation     varchar(16777216),
 FrenchEducation      varchar(16777216),
 EnglishOccupation    varchar(16777216),
 SpanishOccupation    varchar(16777216),
 FrenchOccupation     varchar(16777216),
 HouseOwnerFlag       varchar(16777216),
 NumberCarsOwned      number(38,0),
 AddressLine          varchar(16777216),
 AddressLine2         varchar(16777216),
 Phone                varchar(16777216),
 DateFirstPurchase    date,
 CommuteDistance      varchar(16777216),

 CONSTRAINT PK_DimCustomer PRIMARY KEY ( CustomerKey ),
 CONSTRAINT FK_DimCustomer_401 FOREIGN KEY ( GeographyKey ) REFERENCES JAMES.DimGeography ( GeographyKey )
)
COMMENT = 'Dimension for Customer Data';
