-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.DimProductSubcategory
CREATE TABLE JAMES.DimProductSubcategory
(
 ProductSubcategoryKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ProductSubcategoryAlternateKey number(38,0),
 EnglishProductSubcategoryName  varchar(16777216) NOT NULL,
 SpanishProductSubcategoryName  varchar(16777216) NOT NULL,
 FrenchProductSubcategoryName   varchar(16777216) NOT NULL,
 ProductCategoryKey             number(38,0),

 CONSTRAINT PK_DimProductSubcategory PRIMARY KEY ( ProductSubcategoryKey ),
 CONSTRAINT FK_DimProductSubcategory_409 FOREIGN KEY ( ProductCategoryKey ) REFERENCES JAMES.DimProductCategory ( ProductCategoryKey )
);
