-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.DimGeography
CREATE TABLE JAMES.DimGeography
(
 GeographyKey             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 City                     varchar(16777216),
 StateProvinceCode        varchar(16777216),
 StateProvinceName        varchar(16777216),
 CountryRegionCode        varchar(16777216),
 EnglishCountryRegionName varchar(16777216),
 SpanishCountryRegionName varchar(16777216),
 FrenchCountryRegionName  varchar(16777216),
 PostalCode               varchar(16777216),
 SalesTerritoryKey        number(38,0),
 IpAddressLocator         varchar(16777216),

 CONSTRAINT PK_DimGeography PRIMARY KEY ( GeographyKey )
);
