-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.DimCurrency
CREATE TABLE JAMES.DimCurrency
(
 CurrencyKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Currency Identifier',
 CurrencyAlternateKey varchar(16777216) NOT NULL COMMENT 'Alternate Currency Identifier',
 CurrencyName         varchar(16777216) NOT NULL COMMENT 'Name of the Currency',

 CONSTRAINT PK_DimCurrency PRIMARY KEY ( CurrencyKey )
)
COMMENT = 'Dimension for Currency Data';
