-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.NewFactCurrencyRate
CREATE TABLE JAMES.NewFactCurrencyRate
(
 AverageRate  float,
 CurrencyID   varchar(16777216),
 CurrencyDate date,
 EndOfDayRate float,
 CurrencyKey  number(38,0),
 DateKey      number(38,0),

 CONSTRAINT FK_NewFactCurrencyRate_469 FOREIGN KEY ( CurrencyKey ) REFERENCES JAMES.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_NewFactCurrencyRate_471 FOREIGN KEY ( DateKey ) REFERENCES JAMES.DimDate ( DateKey )
);
