-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.DimReseller
CREATE TABLE JAMES.DimReseller
(
 ResellerKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 GeographyKey         number(38,0),
 ResellerAlternateKey varchar(16777216),
 Phone                varchar(16777216),
 BusinessType         varchar(16777216) NOT NULL,
 ResellerName         varchar(16777216) NOT NULL,
 NumberEmployees      number(38,0),
 OrderFrequency       varchar(16777216),
 OrderMonth           number(38,0),
 FirstOrderYear       number(38,0),
 LastOrderYear        number(38,0),
 ProductLine          varchar(16777216),
 AddressLine1         varchar(16777216),
 AddressLine2         varchar(16777216),
 AnnualSales          number(38,0),
 BankName             varchar(16777216),
 MinPaymentType       number(38,0),
 MinPaymentAmount     number(38,0),
 AnnualRevenue        number(38,0),
 YearOpened           number(38,0),

 CONSTRAINT PK_DimReseller PRIMARY KEY ( ResellerKey ),
 CONSTRAINT FK_DimReseller_411 FOREIGN KEY ( GeographyKey ) REFERENCES JAMES.DimGeography ( GeographyKey )
);
