-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.DimPromotion
CREATE TABLE JAMES.DimPromotion
(
 PromotionKey             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 PromotionAlternateKey    number(38,0),
 EnglishPromotionName     varchar(16777216),
 SpanishPromotionName     varchar(16777216),
 FrenchPromotionName      varchar(16777216),
 DiscountPct              float,
 EnglishPromotionType     varchar(16777216),
 SpanishPromotionType     varchar(16777216),
 FrenchPromotionType      varchar(16777216),
 EnglishPromotionCategory varchar(16777216),
 SpanishPromotionCategory varchar(16777216),
 FrenchPromotionCategory  varchar(16777216),
 MinQty                   number(38,0),
 MaxQty                   number(38,0),

 CONSTRAINT PK_DimPromotion PRIMARY KEY ( PromotionKey )
);
