-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.DimProductPrototype
CREATE TABLE JAMES.DimProductPrototype
(
 DimProductPrototypeKey integer NOT NULL,
 FinishedGoodsFlag      number(38,0) NOT NULL,
 ReorderPoint           number(38,0),
 Weight                 float NOT NULL,
 ModelName              varchar(16777216),

 CONSTRAINT PK_1 PRIMARY KEY ( DimProductPrototypeKey )
);
