-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.DimSalesTerritory
CREATE TABLE JAMES.DimSalesTerritory
(
 SalesTerritoryKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 SalesTerritoryAlternateKey number(38,0),
 SalesTerritoryRegion       varchar(16777216) NOT NULL,
 SalesTerritoryCountry      varchar(16777216) NOT NULL,
 SalesTerritoryGroup        varchar(16777216),

 CONSTRAINT PK_DimSalesTerritory PRIMARY KEY ( SalesTerritoryKey )
)
COMMENT = 'Sales Territory data';
