-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.DimOrganization
CREATE TABLE JAMES.DimOrganization
(
 OrganizationKey       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ParentOrganizationKey number(38,0),
 PercentageOfOwnership varchar(16777216),
 OrganizationName      varchar(16777216),
 CurrencyKey           number(38,0),

 CONSTRAINT PK_DimOrganization PRIMARY KEY ( OrganizationKey )
)
COMMENT = 'Dimension for Organizational Data';
