-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.FactInternetSales
CREATE TABLE JAMES.FactInternetSales
(
 ProductKey             number(38,0) NOT NULL,
 OrderDateKey           number(38,0) NOT NULL,
 DueDateKey             number(38,0) NOT NULL,
 ShipDateKey            number(38,0) NOT NULL,
 CustomerKey            number(38,0) NOT NULL,
 PromotionKey           number(38,0) NOT NULL,
 CurrencyKey            number(38,0) NOT NULL,
 SalesTerritoryKey      number(38,0) NOT NULL,
 SalesOrderNumber       varchar(16777216) NOT NULL,
 SalesOrderLineNumber   number(38,0) NOT NULL,
 RevisionNumber         number(38,0) NOT NULL,
 OrderQuantity          number(38,0) NOT NULL,
 UnitPrice              number(38,0) NOT NULL,
 ExtendedAmount         number(38,0) NOT NULL,
 UnitPriceDiscountPct   float NOT NULL,
 DiscountAmount         float NOT NULL,
 ProductStandardCost    number(38,0) NOT NULL,
 TotalProductCost       number(38,0) NOT NULL,
 SalesAmount            number(38,0) NOT NULL,
 TaxAmt                 number(38,0) NOT NULL,
 Freight                number(38,0) NOT NULL,
 CarrierTrackingNumber  varchar(16777216),
 CustomerPONumber       varchar(16777216),
 DimProductPrototypeKey integer NOT NULL,

 CONSTRAINT FK_FactInternetSales_427 FOREIGN KEY ( ProductKey, DimProductPrototypeKey ) REFERENCES JAMES.DimProduct ( ProductKey, DimProductPrototypeKey ),
 CONSTRAINT FK_FactInternetSales_429 FOREIGN KEY ( CustomerKey ) REFERENCES JAMES.DimCustomer ( CustomerKey ),
 CONSTRAINT FK_FactInternetSales_431 FOREIGN KEY ( PromotionKey ) REFERENCES JAMES.DimPromotion ( PromotionKey ),
 CONSTRAINT FK_FactInternetSales_433 FOREIGN KEY ( CurrencyKey ) REFERENCES JAMES.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_FactInternetSales_435 FOREIGN KEY ( SalesTerritoryKey ) REFERENCES JAMES.DimSalesTerritory ( SalesTerritoryKey ),
 CONSTRAINT FK_FactInternetSales_437 FOREIGN KEY ( OrderDateKey ) REFERENCES JAMES.DimDate ( DateKey ),
 CONSTRAINT FK_FactInternetSales_439 FOREIGN KEY ( DueDateKey ) REFERENCES JAMES.DimDate ( DateKey ),
 CONSTRAINT FK_FactInternetSales_441 FOREIGN KEY ( ShipDateKey ) REFERENCES JAMES.DimDate ( DateKey )
)
COMMENT = 'Fact table to hold Currency Data';
