-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.FactSurveyResponse
CREATE TABLE JAMES.FactSurveyResponse
(
 SurveyResponseKey             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 DateKey                       number(38,0) NOT NULL,
 CustomerKey                   number(38,0) NOT NULL,
 ProductCategoryKey            number(38,0) NOT NULL,
 EnglishProductCategoryName    varchar(16777216) NOT NULL,
 ProductSubcategoryKey         number(38,0) NOT NULL,
 EnglishProductSubcategoryName varchar(16777216) NOT NULL,

 CONSTRAINT FK_FactSurveyResponse_465 FOREIGN KEY ( DateKey ) REFERENCES JAMES.DimDate ( DateKey ),
 CONSTRAINT FK_FactSurveyResponse_467 FOREIGN KEY ( ProductCategoryKey ) REFERENCES JAMES.DimProductCategory ( ProductCategoryKey )
);
