-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.DimProduct
CREATE TABLE JAMES.DimProduct
(
 ProductKey             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 DimProductPrototypeKey integer NOT NULL,
 ProductAlternateKey    varchar(16777216),
 ProductSubcategoryKey  number(38,0),
 WeightUnitMeasureCode  varchar(16777216),
 SizeUnitMeasureCode    varchar(16777216),
 EnglishProductName     varchar(16777216) NOT NULL,
 SpanishProductName     varchar(16777216),
 FrenchProductName      varchar(16777216),
 StandardCost           number(38,0),
 Color                  varchar(16777216) NOT NULL,
 SafetyStockLevel       number(38,0),
 ListPrice              number(38,0),
 Size                   varchar(16777216),
 SizeRange              varchar(16777216),
 DaysToManufacture      number(38,0),
 ProductLine            varchar(16777216),
 DealerPrice            number(38,0),
 Class                  varchar(16777216),
 Style                  varchar(16777216),
 EnglishDescription     varchar(16777216),
 FrenchDescription      varchar(16777216),
 ChineseDescription     varchar(16777216),
 ArabicDescription      varchar(16777216),
 HebrewDescription      varchar(16777216),
 ThaiDescription        varchar(16777216),
 GermanDescription      varchar(16777216),
 JapaneseDescription    varchar(16777216),
 TurkishDescription     varchar(16777216),
 Status                 varchar(16777216),

 CONSTRAINT PK_DimProduct PRIMARY KEY ( ProductKey, DimProductPrototypeKey ),
 CONSTRAINT FK_37 FOREIGN KEY ( DimProductPrototypeKey ) REFERENCES JAMES.DimProductPrototype ( DimProductPrototypeKey ),
 CONSTRAINT FK_DimProduct_407 FOREIGN KEY ( ProductSubcategoryKey ) REFERENCES JAMES.DimProductSubcategory ( ProductSubcategoryKey )
);
