-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: ConcurrentWorkingDemo by james.boncek@sqldbm.com *


-- ************************************** JAMES.FactResellerSales
CREATE TABLE JAMES.FactResellerSales
(
 ProductKey             number(38,0) NOT NULL,
 OrderDateKey           number(38,0) NOT NULL,
 DueDateKey             number(38,0) NOT NULL,
 ShipDateKey            number(38,0) NOT NULL,
 ResellerKey            number(38,0) NOT NULL,
 EmployeeKey            number(38,0) NOT NULL,
 PromotionKey           number(38,0) NOT NULL,
 CurrencyKey            number(38,0) NOT NULL,
 SalesTerritoryKey      number(38,0) NOT NULL,
 SalesOrderNumber       varchar(16777216) NOT NULL,
 SalesOrderLineNumber   number(38,0) NOT NULL,
 RevisionNumber         number(38,0),
 OrderQuantity          number(38,0),
 UnitPrice              number(38,0),
 ExtendedAmount         number(38,0),
 UnitPriceDiscountPct   float,
 DiscountAmount         float,
 ProductStandardCost    number(38,0),
 TotalProductCost       number(38,0),
 SalesAmount            number(38,0),
 TaxAmt                 number(38,0),
 Freight                number(38,0),
 CarrierTrackingNumber  varchar(16777216),
 CustomerPONumber       varchar(16777216),
 DimProductPrototypeKey integer NOT NULL,

 CONSTRAINT FK_FactResellerSales_445 FOREIGN KEY ( ProductKey, DimProductPrototypeKey ) REFERENCES JAMES.DimProduct ( ProductKey, DimProductPrototypeKey ),
 CONSTRAINT FK_FactResellerSales_447 FOREIGN KEY ( ResellerKey ) REFERENCES JAMES.DimReseller ( ResellerKey ),
 CONSTRAINT FK_FactResellerSales_449 FOREIGN KEY ( EmployeeKey ) REFERENCES JAMES.DimEmployee ( EmployeeKey ),
 CONSTRAINT FK_FactResellerSales_451 FOREIGN KEY ( PromotionKey ) REFERENCES JAMES.DimPromotion ( PromotionKey ),
 CONSTRAINT FK_FactResellerSales_453 FOREIGN KEY ( CurrencyKey ) REFERENCES JAMES.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_FactResellerSales_455 FOREIGN KEY ( SalesTerritoryKey ) REFERENCES JAMES.DimSalesTerritory ( SalesTerritoryKey ),
 CONSTRAINT FK_FactResellerSales_457 FOREIGN KEY ( OrderDateKey ) REFERENCES JAMES.DimDate ( DateKey ),
 CONSTRAINT FK_FactResellerSales_459 FOREIGN KEY ( DueDateKey ) REFERENCES JAMES.DimDate ( DateKey ),
 CONSTRAINT FK_FactResellerSales_461 FOREIGN KEY ( ShipDateKey ) REFERENCES JAMES.DimDate ( DateKey )
)
COMMENT = 'Fact data of Reseller Sales';
