-- ***************************************** SqlDBM: Snowflake ****************************************
-- * Generated by SqlDBM: Snowflake export of ''Logical' project sample 1' by james.boncek@sqldbm.com *

-- ************************************** "NATION"
CREATE TABLE "NATION"
(
 "N_NATIONKEY" number(38,0) NOT NULL COMMENT 'Unique nation identifier',
 "N_NAME"      varchar(25) NOT NULL COMMENT 'Name of the nation',
 "N_REGIONKEY" number(38,0) NOT NULL COMMENT 'Region key of the nation',
 "N_COMMENT"   varchar(152) COMMENT 'Comment about the nation',

 CONSTRAINT "PK_1" PRIMARY KEY ( "N_NATIONKEY" )
)
COMMENT = 'Location assigned to customer or supplier';
