-- ***************************************** SqlDBM: Snowflake ****************************************
-- * Generated by SqlDBM: Snowflake export of ''Logical' project sample 1' by james.boncek@sqldbm.com *

-- ************************************** "ONLINE_CUSTOMER"
CREATE TABLE "ONLINE_CUSTOMER"
(
 "C_CUSTKEY"    number(38,0) NOT NULL COMMENT 'Unique customer identifier',
 "OC_DATEREG"   date NOT NULL COMMENT 'Date when the online customer registered their account',
 "OC_LYLTYCODE" number(10,0) NOT NULL COMMENT 'Loyalty program code assigned to the online customer for tracking rewards and benefits',
 "OC_USERNAME"  varchar(16777216) NOT NULL COMMENT 'Unique username chosen by the customer for online account access',

 CONSTRAINT "PK_1" PRIMARY KEY ( "C_CUSTKEY" ),
 CONSTRAINT "FK_9" FOREIGN KEY ( "C_CUSTKEY" ) REFERENCES "CUSTOMER" ( "C_CUSTKEY" )
)
COMMENT = 'Online customer registration and profile information for customers who register through digital channels';
