-- ***************************************** SqlDBM: Snowflake ****************************************
-- * Generated by SqlDBM: Snowflake export of ''Logical' project sample 1' by james.boncek@sqldbm.com *

-- ************************************** "ORDERS"
CREATE TABLE "ORDERS"
(
 "O_ORDERKEY"      number(38,0) NOT NULL COMMENT 'Unique order identifier',
 "O_SUPPKEY"       number(38,0) NOT NULL COMMENT 'Foreign key to Supplier',
 "O_PARTKEY"       number(38,0) NOT NULL COMMENT 'Foreign key to Part',
 "O_ORDERSTATUS"   varchar(1) NOT NULL COMMENT 'Status of the order',
 "O_TOTALPRICE"    number(12,2) NOT NULL COMMENT 'Total price of the order',
 "O_ORDERDATE"     date NOT NULL COMMENT 'Date of the order',
 "O_ORDERPRIORITY" varchar(15) NOT NULL COMMENT 'Priority of the order',
 "O_CLERK"         varchar(15) NOT NULL COMMENT 'Clerk responsible for the order',
 "O_SHIPPRIORITY"  number(38,0) NOT NULL COMMENT 'Shipping priority',
 "O_COMMENT"       varchar(79) COMMENT 'Comment about the order',
 "O_CUSTKEY"       number(38,0) NOT NULL COMMENT 'Foreign key to CUSTOMER (C_CUSTKEY)',

 CONSTRAINT "PK_4" PRIMARY KEY ( "O_ORDERKEY", "O_SUPPKEY", "O_PARTKEY" ),
 CONSTRAINT "FK_4" FOREIGN KEY ( "O_CUSTKEY" ) REFERENCES "CUSTOMER" ( "C_CUSTKEY" ),
 CONSTRAINT "FK_5" FOREIGN KEY ( "O_SUPPKEY" ) REFERENCES "SUPPLIER" ( "S_SUPPKEY" ),
 CONSTRAINT "FK_7" FOREIGN KEY ( "O_PARTKEY" ) REFERENCES "PART" ( "P_PARTKEY" )
)
COMMENT = 'Parts sold to a customer';
