-- ***************************************** SqlDBM: Snowflake ****************************************
-- * Generated by SqlDBM: Snowflake export of ''Logical' project sample 1' by james.boncek@sqldbm.com *

-- ************************************** "PART"
CREATE TABLE "PART"
(
 "P_PARTKEY"     number(38,0) NOT NULL COMMENT 'Unique part identifier',
 "P_NAME"        varchar(16777216) NOT NULL COMMENT 'Name of the part',
 "P_MFGR"        varchar(16777216) NOT NULL COMMENT 'Manufacturer of the part',
 "P_BRAND"       varchar(16777216) NOT NULL COMMENT 'Brand of the part',
 "P_TYPE"        varchar(16777216) NOT NULL COMMENT 'Type of the part',
 "P_SIZE"        number(38,0) NOT NULL COMMENT 'Size of the part',
 "P_CONTAINER"   varchar(16777216) NOT NULL COMMENT 'Container type',
 "P_RETAILPRICE" number(12,2) NOT NULL COMMENT 'Retail price of the part',
 "P_COMMENT"     varchar(16777216) COMMENT 'Comment about the part',

 CONSTRAINT "PK_1" PRIMARY KEY ( "P_PARTKEY" )
)
COMMENT = 'Parts we distribute';
