-- ***************************************** SqlDBM: Snowflake ****************************************
-- * Generated by SqlDBM: Snowflake export of ''Logical' project sample 1' by james.boncek@sqldbm.com *

-- ************************************** "RETAIL_CUSTOMER"
CREATE TABLE "RETAIL_CUSTOMER"
(
 "C_CUSTKEY"       number(38,0) NOT NULL COMMENT 'Unique customer identifier',
 "RC_DATEREGISTR"  date NOT NULL COMMENT 'Date when the retail customer registered at a physical store location',
 "RC_HASLYLTYCARD" boolean NOT NULL COMMENT 'Boolean flag indicating whether the retail customer has a physical loyalty card',
 "RC_LYLTYCARD"    number(10,0) NOT NULL COMMENT 'Physical loyalty card number for retail customers who opted for the loyalty program',

 CONSTRAINT "PK_1" PRIMARY KEY ( "C_CUSTKEY" ),
 CONSTRAINT "FK_10" FOREIGN KEY ( "C_CUSTKEY" ) REFERENCES "CUSTOMER" ( "C_CUSTKEY" )
)
COMMENT = 'Retail customer information for customers who register through physical store locations';
