-- ***************************************** SqlDBM: Snowflake ****************************************
-- * Generated by SqlDBM: Snowflake export of ''Logical' project sample 1' by james.boncek@sqldbm.com *

-- ************************************** "SUPPLIER"
CREATE TABLE "SUPPLIER"
(
 "S_SUPPKEY"   number(38,0) NOT NULL COMMENT 'Unique supplier identifier',
 "S_NAME"      varchar(16777216) NOT NULL COMMENT 'Name of the supplier',
 "S_ADDRESS"   varchar(16777216) NOT NULL COMMENT 'Address of the supplier',
 "S_PHONE"     varchar(16777216) NOT NULL COMMENT 'Phone number of the supplier',
 "S_ACCTBAL"   number(12,2) NOT NULL COMMENT 'Account balance of the supplier',
 "S_COMMENT"   varchar(16777216) COMMENT 'Comment about the supplier',
 "S_NATIONKEY" number(38,0) NOT NULL COMMENT 'Foreign key to Location',

 CONSTRAINT "PK_1" PRIMARY KEY ( "S_SUPPKEY" ),
 CONSTRAINT "FK_3" FOREIGN KEY ( "S_NATIONKEY" ) REFERENCES "NATION" ( "N_NATIONKEY" )
)
COMMENT = 'Suppliers who we buy from';
