-- ************************** SqlDBM: Snowflake *************************
-- **** Generated by SqlDBM: flag change 2 by james.boncek@sqldbm.com ***

-- ************************************** table_1
CREATE TABLE table_1
(

);
